[package]
name = "moonhare_graphics"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
moonhare_window = { path = "../moonhare_window" }
glium = "0.36"
state = "0.6"
lazy_static = "*"