[workspace]
resolver = "3"
members = [
    "moonhare_engine", "moonhare_event", 
    "moonhare_graphics", 
    "moonhare_log", 
    "moonhare_window", 
    "playground"
]

[workspace.package]
version = "0.1.0"
authors = ["LunarAkai"]


