[package]
name = "moonhare_window"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
moonhare_log = { path = "../moonhare_log" }
moonhare_event = { path = "../moonhare_event" }
gtk4 = "*"
winit = "0.30"
glfw = "*"